name: Symfony CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_mysql
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-dev --optimize-autoloader

      - name: Dump environment variables for production
        run: composer dump-env prod
        env:
          APP_ENV: prod
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run PHP lint
        run: find src tests -name "*.php" -exec php -l {} \;

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Audit de sécurité
        run: composer audit --format=json --no-interaction
        continue-on-error: true

      - name: Build artifact
        run: |
          mkdir -p build
          cp -R * build/
          tar -czf build.tar.gz build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-build
          path: build.tar.gz
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: symfony-artifact
          path: symfony-artifact-r1.tar.gz
